spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://shop-authorization-server:8081
        client:
          shop-test-client:
            registration:
              client-id: shop-test
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}testing123"
              scopes:
                - products:read
                - products:write
                - products:stock:write
                - categories:read
                - categories:write
            token:
              access-token-time-to-live: 15m
          shop-ordering-service-client:
            registration:
              client-id: shop-ordering-service
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}secret123"
              scopes:
                - products:read
